repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [-x]
        files: \.(sh|bash)$

  - repo: https://github.com/mvdan/shfmt-py
    rev: v3.10.0
    hooks:
      - id: shfmt
        args: [-w, -i, 4, -bn]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=500]
